version: '3.9'

services:
  api:
    build:
      context: ./../
      dockerfile: ./../Dockerfile
    restart: always
    ports:
      - "8080:5001"

  postgres:
    image: 'postgres:15.2'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: parsa
      POSTGRES_PASSWORD: parsa
      POSTGRES_DB: rebottle
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
      - .:/docker-entrypoint-initdb.d/