openapi: 3.0.3
info:
  title: Rebottle
  description: Rebottle api
  version: 1.0.0
servers:
  - url: 'http://localhost:5001/v1'
tags:
  - name: user
  - name: auth
  - name: pickup
  - name: driver
    description: user's pickup

components:
  schemas:
    PickupStatus:
      $ref: './schemas/PickupStatus.yaml'
    UserStatus:
      $ref: './schemas/UserStatus.yaml'
    UserEmailStatus:
      $ref: './schemas/UserEmailStatus.yaml'
    DriverStatus:
      $ref: './schemas/DriverStatus.yaml'
    SignupBasePayload:
      $ref: './schemas/SignupBasePayload.yaml'
    SignupDriverPayload:
      $ref: './schemas/SignupDriverPayload.yaml'

  responses:
    GeneralResponse:
      $ref: "./responses/GeneralResponse.yaml"
    # Todo: can not import all of the responses here? So we would have responses.$ref here.

paths:
  /user:
    $ref: './paths/user/user.yaml'

  /signup:
    $ref: './paths/signup/signup.yaml'

  /signup-driver:
    post:
      tags:
        - auth
      summary: driver signup
      description: driver signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: './schemas/SignupBasePayload.yaml'
                - type: object
                  properties:
                    license_no:
                      description: license number
                      required: true
                      type: string
                      default: "11111111"
#              $ref: './schemas/SignupDriverPayload.yaml'



      responses:



  /verify-signup:
    $ref: './paths/verify-signup/verify-signup.yaml'

  /verify-signup-driver:
    $ref: './paths/verify-signup-driver/verify-signup-driver.yaml'

  /login:
    $ref: './paths/login/login.yaml'

  /token:
    $ref: './paths/token/token.yaml'

  /pickup:
    $ref: './paths/pickup/pickups.yaml'

  "/pickup/{pickupId}":
    $ref: './paths/pickup/pickup.yaml'

  /driver/{id}:
    put:
      tags:
        - driver
      summary: "Update driver info"
      description: "Update driver info"
      responses:
        "200":

