openapi: 3.0.3
info:
  title: Rebottle
  description: Rebottle api
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:5001/v1'
tags:
  - name: user
  - name: auth
  - name: pickup
    description: user's pickup

components:
  schemas:
    PickupStatus:
      $ref: './schemas/PickupStatus.yaml'
    UserStatus:
      $ref: './schemas/UserStatus.yaml'
    UserEmailStatus:
      $ref: './schemas/UserEmailStatus.yaml'
    DriverStatus:
      $ref: './schemas/DriverStatus.yaml'

  responses:
    GeneralResponse:
      $ref: "./responses/GeneralResponse.yaml"
    # Todo: can not import all of the responses here? So we would have responses.$ref here.

paths:
  /user:
    $ref: './paths/user/user.yaml'

  /signup:
    #    $ref: './paths/signup/signup.yaml'
    post:
      tags:
        - auth
      summary: "signup user and send OTP"
      description: "signup user and send OTP"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                phone:
                  description: user phone number
                  required: true
                  type: string
                  default: "09111111111"
                first_name:
                  description: first name
                  required: true
                  type: string
                  default: "paari"
                last_name:
                  description: last name
                  required: true
                  type: string
                  default: "paari2"
                email:
                  description: email
                  required: false
                  type: string
                  default: "test@test.com"
                password:
                  description: password
                  required: true
                  type: string
                  default: "test@test.com"
                province:
                  description: province
                  required: true
                  type: string
                  default: Tehran
                city:
                  description: city
                  required: true
                  type: string
                  default: Tehran
                street:
                  description: street
                  required: true
                  type: string
                  default: some street
                alley:
                  description: alley
                  required: true
                  type: string
                  default: some alley
                apartment_plate:
                  description: apartment plate
                  required: true
                  type: number
                  default: 14
                apartment_no:
                  description: apartment number
                  required: true
                  type: number
                  default: 3
                postal_code:
                  description: postal code
                  required: true
                  type: string
                  default: 11222222


      responses:
        "200":
          description: "success response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
        "400":
          $ref: '../../responses/GeneralResponse.yaml'

  /verify-signup:
    $ref: './paths/verify-signup/verify-signup.yaml'

  /login:
    $ref: './paths/login/login.yaml'

  /pickup:
    $ref: './paths/pickup/pickups.yaml'

  "/pickup/{pickupId}":
    $ref: './paths/pickup/pickup.yaml'

